import React from 'react';
import Link from 'next/link';

export default function RefundPolicy() {
    return (
        <div className="min-h-screen bg-white text-black px-6 py-10 sm:px-12 lg:px-32 ">
            <h1 className="text-3xl font-bold border-b-2 border-black pb-3 mb-6">Return & Refund Policy</h1>
            
            <p className="text-lg mb-4">Our Return and Refund Policy was last updated on <strong>17/03/2025</strong>.</p>
            <p className="text-lg mb-4">Thank you for shopping at <strong>Bootup AI</strong>.</p>
            <p className="text-lg mb-6">The following terms are applicable for any products that you have purchased from us.</p>

            <h2 className="text-2xl font-semibold mb-3">Eligibility for Refunds</h2>
            <p className="mb-4">We offer refunds under the following circumstances:</p>
            <ul className="list-disc pl-6 space-y-2 mb-6">
                <li>If the service is not delivered as promised due to an error on our end.</li>
                <li>If a technical issue caused by our platform prevents you from accessing the features you paid for, and the issue cannot be resolved within a reasonable timeframe.</li>
                <li>If you cancel your subscription within the refund period outlined below.</li>
            </ul>

            <h2 className="text-2xl font-semibold mb-3">Refund Period</h2>
            <p className="mb-6">Refund requests must be made within <strong>30</strong> days of the payment date. Requests made after this period will not be eligible for a refund.</p>

            <h2 className="text-2xl font-semibold mb-3">Non-Refundable Cases</h2>
            <p className="mb-4">Refunds will not be granted under the following conditions:</p>
            <ul className="list-disc pl-6 space-y-2 mb-6">
                <li>If you change your mind after purchasing a subscription or service.</li>
                <li>If you fail to use the service during the subscription period.</li>
                <li>If the issue is caused by third-party software or tools not affiliated with our platform.</li>
            </ul>

            <h2 className="text-2xl font-semibold mb-3">Refund Process</h2>
            <p className="mb-4">To request a refund, please follow these steps:</p>
            <ol className="list-decimal pl-6 space-y-2 mb-6">
                <li>Contact our support team at <a href="mailto:manojkumarcpyk@gmail.com" className="text-blue-600 hover:underline">manojkumarcpyk@gmail.com</a>.</li>
                <li>Provide your payment receipt, order ID, and a detailed explanation of the issue.</li>
                <li>Our team will review your request and respond within 3-5 business days.</li>
                <li>If your request is approved, the refund will be processed to your original payment method within 7-10 business days.</li>
                <li>This has been generated by <a href="https://dodopayments.com" className="text-blue-600 hover:underline">dodopayments.com</a></li>
            </ol>

            <h2 className="text-2xl font-semibold mb-3">Contact Us</h2>
            <p>If you have any questions about this Refund Policy or require assistance, please reach out to us:</p>
            <p>Email: <a href="mailto:manojkumarcpyk@gmail.com" className="text-blue-600 hover:underline">manojkumarcpyk@gmail.com</a></p>
        </div>
    );
}
